### ISSUE TITLE
SearchPage에서 키보드가 내려간 후 셀 터치 미작동 문제

### ISSUE THREAD

**Issue by angwoo0503** [iOS-Oppenheimer/Weather_Fairy#46]
# 🚨Issue🚨
**SearchPage에서 빈공간 터치 시 키보드는 내려가나 셀 터치가 되지 않는 문제**

![Group 165](https://github.com/iOS-Oppenheimer/Weather_Fairy/assets/136118540/b27f37b5-a37e-4f48-ac4a-7cddd80cdc1e)

# Description
```swift
    override func viewDidLoad() {
        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(handleTap(_:)))
        view.addGestureRecognizer(tapGesture)
    }
    @objc func handleTap(_ sender: UITapGestureRecognizer) {
        view.endEditing(true)
    }
```
SearchPage에서 SearchBar로 텍스트를 작성하고 키보드가 내려가게 하기 위해 빈 공간을 터치하면 키보드가 내려가는 기능을 구현하였으나 그 이후의 TableView 내에서의 터치가 작동하지 않아 Cell을 선택할 수 없는 문제가 발생함.

**Comment by angwoo0503** [comment]
# 문제 원인
- 키보드를 내리고 나서 테이블 뷰를 터치할 수 없는 문제는 터치 제스처의 우선순위와 관련이 있음.
- 키보드를 내리기 위해 빈 공간을 탭하는 터치 제스처와 테이블뷰 셀을 선택하는 터치 제스처 사이의 충돌이 발생함.

# 해결 방법
## cancelsTouchesInView 속성 사용
```swift
    override func viewDidLoad() {
        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(handleTap(_:)))
        view.addGestureRecognizer(tapGesture)
        tapGesture.cancelsTouchesInView = false // false로 설정
    }
    @objc func handleTap(_ sender: UITapGestureRecognizer) {
        view.endEditing(true)
    }
```
UIGestureRecognizer의 cancelsTouchesInView 속성을 사용하여 터치 이벤트가 키보드를 내리는 터치 제스처에 의해 취소되지 않도록 설정하여 키보드를 내리는 터치 이벤트가 다른 터치 이벤트를 취소하지 않으므로 테이블뷰를 터치할 수 있게 됨.

![시뮬녹화](https://github.com/iOS-Oppenheimer/Weather_Fairy/assets/136118540/ec99f221-42bf-45ec-b7d6-35c9d0b5d087)


## 다른 해결 방안
### 두 개의 서로 다른 터치 제스처를 사용
터치 제스처를 다른 두 개를 사용하여 키보드를 내리는 터치와 테이블뷰를 터치하는 터치를 구분함. 예를 들어 키보드를 내리는 터치 제스처와 테이블뷰를 터치하는 터치 제스처를 서로 다른 객체로 만들고 각각 관리함.

```swift
// 키보드를 내리는 탭 제스처 생성
let keyboardDismissGesture = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboard(_:)))
view.addGestureRecognizer(keyboardDismissGesture)
// 테이블뷰 터치 제스처 생성
let tableViewTapGesture = UITapGestureRecognizer(target: self, action: #selector(handleTableViewTap(_:)))
tableView.addGestureRecognizer(tableViewTapGesture)
// 키보드를 내리는 탭 제스처 핸들러
@objc func dismissKeyboard(_ sender: UITapGestureRecognizer) {view.endEditing(true)}
// 테이블뷰 터치 제스처 핸들러
@objc func handleTableViewTap(_ sender: UITapGestureRecognizer) {
// 테이블뷰 셀을 선택하는 로직을 작성...
}
```

## 아쉬운 점 및 보완하고 싶은 점
- 키보드가 올라왔을 때 셀을 터치해도 셀 터치가 되지 않고 키보드만 내려가게 하고 싶었으나 키보드가 올라와진 상태에서 셀을 터치하면 셀 터치가 되어 화면이 넘어감. 
- 원하던 기능을 구현하지는 못했으나 스크롤 시 키보드가 내려가는 기능을 추가적으로 구현하여 키보드로 가려졌던 아래의 Cell들도 사용자가 쉽게 보고 터치할 수 있도록 구현함.

# 해결에 참고한 문서들
- https://developer.apple.com/documentation/uikit/uigesturerecognizer/1624218-cancelstouchesinview
- https://velog.io/@boms2/Swift-cancelsTouchesInView%EA%B0%80-%EB%AD%90%EC%A3%A0
- https://baechukim.tistory.com/134

**Comment by Luna828** [comment]
확인했습니다~

**Comment by angwoo0503** [comment]
해결 완료~~
